### ISSUE TITLE
Request  to delet Unnecessary Folde

### ISSUE THREAD

**Issue by Ahsan-mw** [kwakyebrilliant/sonnet#1]
### Request to Delete Unnecessary Folder

**Folder Path**: `lib/new`

**Reason for Deletion**:. Removing this folder will help clean up the repository and avoid confusion for future contributors.

Please consider deleting this folder to maintain a clean and organized codebase.

Thank you!

**Comment by kwakyebrilliant** [comment]
Great!! doing that
